steps:
  # Build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/genbook-test-285222/genbook-test', '.']
  
  # Push image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/genbook-test-285222/genbook-test']

  # Copy the app config file from GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://genbook-test/application.properties', 'application.properties']

  # Prepare configmap yaml
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        kubectl create configmap hello-world-config --from-file application.properties --dry-run -o yaml > configmap.yaml
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=genbook-test-cluster'

  # Apply configmap
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'configmap.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=genbook-test-cluster'    

  # Apply deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=genbook-test-cluster'    